### PR TITLE
Negative values reporting and handling

### PR DESCRIPTION
**Pull request by Tinkaa**
@joseepoirier @milanoleonardo  Added quality checks for negative values, decreasing cumulative values, and missing dates

My reasoning of handling these in the different data sources, but ofc open for discussion:

- WHO: want a warning if negative values in new cases/deaths and if decreasing value in cumulative cases/deaths, but we don’t want to change these values since they are adjustments.  Imo not needed to add extra warning in report if adjustment in cumulative was made since the last report. Possibly valuable for the 7-day average in the report to add a flag if negative values occurred, so added a binary metric for this in the` report_metrics\{country_iso3}_results.csv`

- Subnational: same reasoning as WHO, but only reporting cumulative numbers so no extra flag needed in report.

- Bucky: in principle negative values or decreasing cumulative values should never occur since this are model outputs. So print the occurrences of negative/decreasing values on console and understand how to handle them before producing the reports. 

Also added a check for WHO and Subnational to see if there was any data the last 14 days. But have to think if this is the info we want and how we want to use it

### CODE REVIEW

**Comment by Tinkaa** [comment]
@joseepoirier talking about negatvie values, we still got this PR😅Do you think we should change the approach or merge?

**Comment by joseepoirier** [comment]
Reporting negative values in the key messages is sound. I am not fully comfortable with censoring negative values but if you, Leonardo and Matt have discussed it and are in agreement it is a reasonable approach, let's do it.

**Comment by Tinkaa** [comment]
what you mean with censoring?

**Comment by Tinkaa** [comment]
For archiving: the negative values are caused by small integration errors in the model. Meaning that those negative values actually indicate 0. This is thus something that should already be removed in the model and is now also done that way (in [`postprocess.py` of pa-ocha-bucky](https://github.com/OCHA-DAP/pa-ocha-bucky/blob/ocha/bucky/postprocess.py))

**Comment by Tinkaa** [comment]
@joseepoirier gonna merge but if you think we should change anything, let me know/start an issue

**Pull request merged**
